
export const FETCH_RANDOM_PHOTO = 'FETCH_RANDOM_PHOTO';
export const FETCH_RANDOM_PHOTO_SUCCESS = 'FETCH_RANDOM_PHOTO_SUCCESS';
export const FETCH_RANDOM_PHOTO_FAILURE = 'FETCH_RANDOM_PHOTO_FAILURE';

export const APPROVE_PHOTO = 'APPROVE_PHOTO';
export const APPROVE_PHOTO_SUCCESS = 'APPROVE_PHOTO_SUCCESS';
export const DECLINE_PHOTO = 'DECLINE_PHOTO';
export const DECLINE_PHOTO_SUCCESS = 'DECLINE_PHOTO_SUCCESS';
